site_name: Documentación de Leishmaniapp

plugins:
  - glightbox
  - with-pdf:
      output_path: document.pdf
      enabled_if_env: ENABLE_PDF_EXPORT

theme:
  name: "material"
  logo: assets/index/leishmaniapp_neumorphic_light.webp
  favicon: assets/index/leishmaniapp_neumorphic_light.webp
  palette:
    primary: custom

extra_css:
  - stylesheets/fonts.css
  - stylesheets/color.css

markdown_extensions:
  - def_list
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true

nav:
  - index.md
  - diseases.md
  - models.md
  - schema.md
  - cloud.md
  # - application.md
  - lam.md
  - debugger.md
